# Generated by Django 4.2.23 on 2025-08-16 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateRelatorio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome identificador do template de relatório",
                        max_length=200,
                        verbose_name="Nome do Template",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do que o relatório apresenta",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "tipo_relatorio",
                    models.CharField(
                        choices=[
                            ("processos", "Relatório de Processos"),
                            ("clientes", "Relatório de Clientes"),
                            ("financeiro", "Relatório Financeiro"),
                            ("produtividade", "Relatório de Produtividade"),
                            ("prazos", "Relatório de Prazos"),
                            ("documentos", "Relatório de Documentos"),
                            ("personalizado", "Relatório Personalizado"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Relatório",
                    ),
                ),
                (
                    "formato_saida",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("html", "HTML"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="Formato de Saída",
                    ),
                ),
                (
                    "campos_selecionados",
                    models.JSONField(
                        default=list,
                        help_text="Lista de campos que serão incluídos no relatório",
                        verbose_name="Campos Selecionados",
                    ),
                ),
                (
                    "filtros_padrao",
                    models.JSONField(
                        default=dict,
                        help_text="Filtros que serão aplicados por padrão no relatório",
                        verbose_name="Filtros Padrão",
                    ),
                ),
                (
                    "ordenacao_padrao",
                    models.JSONField(
                        default=list,
                        help_text="Campos e direção de ordenação padrão",
                        verbose_name="Ordenação Padrão",
                    ),
                ),
                (
                    "agrupamento",
                    models.JSONField(
                        default=list,
                        help_text="Campos para agrupamento de dados",
                        verbose_name="Agrupamento",
                    ),
                ),
                (
                    "configuracoes_layout",
                    models.JSONField(
                        default=dict,
                        help_text="Configurações visuais do relatório (cores, fontes, etc.)",
                        verbose_name="Configurações de Layout",
                    ),
                ),
                (
                    "publico",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, o template estará disponível para todos os usuários",
                        verbose_name="Público",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario_criador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates_relatorio",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Criador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Relatório",
                "verbose_name_plural": "Templates de Relatórios",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="FiltroSalvo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Filtro"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "tipo_filtro",
                    models.CharField(
                        choices=[
                            ("processos", "Processos"),
                            ("clientes", "Clientes"),
                            ("documentos", "Documentos"),
                            ("financeiro", "Financeiro"),
                            ("prazos", "Prazos"),
                            ("relatorios", "Relatórios"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Filtro",
                    ),
                ),
                (
                    "parametros_filtro",
                    models.JSONField(
                        default=dict,
                        help_text="Configurações específicas do filtro",
                        verbose_name="Parâmetros do Filtro",
                    ),
                ),
                ("publico", models.BooleanField(default=False, verbose_name="Público")),
                (
                    "favorito",
                    models.BooleanField(default=False, verbose_name="Favorito"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filtros_salvos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filtro Salvo",
                "verbose_name_plural": "Filtros Salvos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ExecucaoRelatorio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parametros_execucao",
                    models.JSONField(
                        default=dict,
                        help_text="Filtros e parâmetros específicos desta execução",
                        verbose_name="Parâmetros de Execução",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processando", "Processando"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="processando",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_execucao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Execução"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Conclusão"
                    ),
                ),
                (
                    "tempo_processamento",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Tempo de Processamento"
                    ),
                ),
                (
                    "total_registros",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantidade de registros incluídos no relatório",
                        null=True,
                        verbose_name="Total de Registros",
                    ),
                ),
                (
                    "tamanho_arquivo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tamanho do Arquivo (bytes)"
                    ),
                ),
                (
                    "caminho_arquivo",
                    models.CharField(
                        blank=True,
                        help_text="Caminho onde o arquivo foi salvo",
                        max_length=500,
                        null=True,
                        verbose_name="Caminho do Arquivo",
                    ),
                ),
                (
                    "mensagem_erro",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de Erro"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execucoes",
                        to="relatorios.templaterelatorio",
                        verbose_name="Template",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execucoes_relatorio",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execução de Relatório",
                "verbose_name_plural": "Execuções de Relatórios",
                "ordering": ["-data_execucao"],
            },
        ),
        migrations.CreateModel(
            name="DashboardPersonalizado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do Dashboard"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "configuracao_widgets",
                    models.JSONField(
                        default=list,
                        help_text="Lista de widgets e suas configurações",
                        verbose_name="Configuração dos Widgets",
                    ),
                ),
                (
                    "layout",
                    models.JSONField(
                        default=dict,
                        help_text="Configurações de layout do dashboard",
                        verbose_name="Layout",
                    ),
                ),
                ("publico", models.BooleanField(default=False, verbose_name="Público")),
                (
                    "padrao",
                    models.BooleanField(
                        default=False,
                        help_text="Se marcado, será o dashboard padrão do usuário",
                        verbose_name="Dashboard Padrão",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Personalizado",
                "verbose_name_plural": "Dashboards Personalizados",
                "ordering": ["nome"],
            },
        ),
        migrations.AddIndex(
            model_name="templaterelatorio",
            index=models.Index(
                fields=["tipo_relatorio"], name="relatorios__tipo_re_487371_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templaterelatorio",
            index=models.Index(
                fields=["usuario_criador"], name="relatorios__usuario_566472_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="templaterelatorio",
            index=models.Index(
                fields=["publico", "ativo"], name="relatorios__publico_bd4914_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filtrosalvo",
            index=models.Index(
                fields=["usuario", "tipo_filtro"], name="relatorios__usuario_4a9917_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filtrosalvo",
            index=models.Index(
                fields=["publico"], name="relatorios__publico_ece326_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filtrosalvo",
            index=models.Index(
                fields=["favorito"], name="relatorios__favorit_220d79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="execucaorelatorio",
            index=models.Index(
                fields=["template", "-data_execucao"],
                name="relatorios__templat_e67b7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="execucaorelatorio",
            index=models.Index(
                fields=["usuario", "-data_execucao"],
                name="relatorios__usuario_905555_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="execucaorelatorio",
            index=models.Index(fields=["status"], name="relatorios__status_6e6b5a_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboardpersonalizado",
            index=models.Index(
                fields=["usuario"], name="relatorios__usuario_8f2561_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardpersonalizado",
            index=models.Index(
                fields=["publico", "ativo"], name="relatorios__publico_94bc2d_idx"
            ),
        ),
    ]
