# Generated by Django 4.2.25 on 2025-11-12 12:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("relatorios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendamentoRelatorio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome do Agendamento"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "tipo_agendamento",
                    models.CharField(
                        choices=[
                            ("diario", "Diário"),
                            ("semanal", "Semanal"),
                            ("mensal", "Mensal"),
                            ("personalizado", "Personalizado"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de Agendamento",
                    ),
                ),
                (
                    "configuracao",
                    models.JSONField(
                        default=dict, verbose_name="Configuração do Agendamento"
                    ),
                ),
                (
                    "proxima_execucao",
                    models.DateTimeField(verbose_name="Próxima Execução"),
                ),
                (
                    "ultima_execucao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última Execução"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("pausado", "Pausado"),
                            ("cancelado", "Cancelado"),
                            ("concluido", "Concluído"),
                        ],
                        default="ativo",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "destinatarios",
                    models.JSONField(
                        default=list,
                        help_text="Lista de emails para envio automático",
                        verbose_name="Destinatários",
                    ),
                ),
                (
                    "manter_historico",
                    models.BooleanField(
                        default=True,
                        help_text="Manter histórico das execuções agendadas",
                        verbose_name="Manter Histórico",
                    ),
                ),
                (
                    "dias_manter_historico",
                    models.IntegerField(
                        default=90,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                        verbose_name="Dias para Manter Histórico",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento de Relatório",
                "verbose_name_plural": "Agendamentos de Relatórios",
                "ordering": ["proxima_execucao"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoExportacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome da Configuração"
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("html", "HTML"),
                        ],
                        max_length=10,
                        verbose_name="Formato de Saída",
                    ),
                ),
                (
                    "configuracoes",
                    models.JSONField(
                        default=dict, verbose_name="Configurações de Exportação"
                    ),
                ),
                (
                    "orientacao_pagina",
                    models.CharField(
                        choices=[("portrait", "Retrato"), ("landscape", "Paisagem")],
                        default="portrait",
                        max_length=10,
                        verbose_name="Orientação da Página",
                    ),
                ),
                (
                    "incluir_cabecalho",
                    models.BooleanField(default=True, verbose_name="Incluir Cabeçalho"),
                ),
                (
                    "incluir_rodape",
                    models.BooleanField(default=True, verbose_name="Incluir Rodapé"),
                ),
                (
                    "auto_filter",
                    models.BooleanField(default=True, verbose_name="Auto Filtro"),
                ),
                (
                    "freeze_panes",
                    models.BooleanField(default=True, verbose_name="Congelar Painéis"),
                ),
                ("publico", models.BooleanField(default=False, verbose_name="Público")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Exportação",
                "verbose_name_plural": "Configurações de Exportação",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="FiltroAvancado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Filtro"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "tipo_filtro",
                    models.CharField(
                        choices=[
                            ("processo", "Processo"),
                            ("cliente", "Cliente"),
                            ("financeiro", "Financeiro"),
                            ("documento", "Documento"),
                            ("usuario", "Usuário"),
                            ("data", "Data"),
                            ("status", "Status"),
                            ("personalizado", "Personalizado"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de Filtro",
                    ),
                ),
                (
                    "condicoes",
                    models.JSONField(
                        default=list,
                        help_text="Lista de condições para aplicação do filtro",
                        verbose_name="Condições do Filtro",
                    ),
                ),
                (
                    "publico",
                    models.BooleanField(
                        default=False,
                        help_text="Disponível para todos os usuários",
                        verbose_name="Público",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Filtro Avançado",
                "verbose_name_plural": "Filtros Avançados",
                "ordering": ["nome"],
            },
        ),
        migrations.RemoveIndex(
            model_name="execucaorelatorio",
            name="relatorios__templat_e67b7f_idx",
        ),
        migrations.RemoveIndex(
            model_name="execucaorelatorio",
            name="relatorios__usuario_905555_idx",
        ),
        migrations.RemoveField(
            model_name="execucaorelatorio",
            name="caminho_arquivo",
        ),
        migrations.RemoveField(
            model_name="execucaorelatorio",
            name="observacoes",
        ),
        migrations.RemoveField(
            model_name="execucaorelatorio",
            name="tempo_processamento",
        ),
        migrations.AddField(
            model_name="execucaorelatorio",
            name="arquivo_gerado",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="relatorios/%Y/%m/%d/",
                verbose_name="Arquivo Gerado",
            ),
        ),
        migrations.AddField(
            model_name="execucaorelatorio",
            name="duracao_execucao",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Duração da Execução"
            ),
        ),
        migrations.AlterField(
            model_name="execucaorelatorio",
            name="tamanho_arquivo",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Tamanho do Arquivo"
            ),
        ),
        migrations.AlterField(
            model_name="execucaorelatorio",
            name="total_registros",
            field=models.IntegerField(default=0, verbose_name="Total de Registros"),
        ),
        migrations.AddIndex(
            model_name="execucaorelatorio",
            index=models.Index(
                fields=["template"], name="relatorios__templat_e7b22b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="execucaorelatorio",
            index=models.Index(
                fields=["usuario"], name="relatorios__usuario_609eb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="execucaorelatorio",
            index=models.Index(
                fields=["data_execucao"], name="relatorios__data_ex_3a0452_idx"
            ),
        ),
        migrations.AddField(
            model_name="filtroavancado",
            name="usuario_criador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filtros_avancados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Criador",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoexportacao",
            name="usuario_criador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configuracoes_exportacao",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Criador",
            ),
        ),
        migrations.AddField(
            model_name="agendamentorelatorio",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos",
                to="relatorios.templaterelatorio",
                verbose_name="Template",
            ),
        ),
        migrations.AddField(
            model_name="agendamentorelatorio",
            name="usuario_criador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendamentos_relatorio",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Criador",
            ),
        ),
        migrations.AddIndex(
            model_name="filtroavancado",
            index=models.Index(
                fields=["tipo_filtro"], name="relatorios__tipo_fi_732b06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filtroavancado",
            index=models.Index(
                fields=["usuario_criador"], name="relatorios__usuario_0ad3a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="filtroavancado",
            index=models.Index(
                fields=["publico"], name="relatorios__publico_22b2a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configuracaoexportacao",
            index=models.Index(
                fields=["formato"], name="relatorios__formato_7ff6c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configuracaoexportacao",
            index=models.Index(
                fields=["usuario_criador"], name="relatorios__usuario_189a82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamentorelatorio",
            index=models.Index(
                fields=["template"], name="relatorios__templat_88c72f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamentorelatorio",
            index=models.Index(
                fields=["usuario_criador"], name="relatorios__usuario_0e8f56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamentorelatorio",
            index=models.Index(fields=["status"], name="relatorios__status_c13d80_idx"),
        ),
        migrations.AddIndex(
            model_name="agendamentorelatorio",
            index=models.Index(
                fields=["proxima_execucao"], name="relatorios__proxima_63292f_idx"
            ),
        ),
    ]
