# Generated by Django 4.2.23 on 2025-08-16 19:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaDireito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Nome da Área",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único para identificação",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        default="#28a745",
                        help_text="Cor em hexadecimal para identificação visual",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        default="bi-scales",
                        help_text="Classe do ícone Bootstrap Icons",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="areas_direito_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área do Direito",
                "verbose_name_plural": "Áreas do Direito",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="TipoProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Nome do Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do tipo de processo",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único para identificação (ex: CIV, TRAB, CRIM)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        default="#007bff",
                        help_text="Cor em hexadecimal para identificação visual",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        default="bi-folder",
                        help_text="Classe do ícone Bootstrap Icons",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tipos_processo_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Processo",
                "verbose_name_plural": "Tipos de Processo",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="StatusProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Nome do Status",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código único para identificação",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        default="#6c757d",
                        help_text="Cor em hexadecimal para identificação visual",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        default="bi-circle",
                        help_text="Classe do ícone Bootstrap Icons",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "is_inicial",
                    models.BooleanField(
                        default=False,
                        help_text="Define se este é o status padrão para novos processos",
                        verbose_name="Status Inicial",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Define se este status indica processo encerrado",
                        verbose_name="Status Final",
                    ),
                ),
                (
                    "permite_edicao",
                    models.BooleanField(
                        default=True,
                        help_text="Define se processos com este status podem ser editados",
                        verbose_name="Permite Edição",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_processo_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status de Processo",
                "verbose_name_plural": "Status de Processo",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="ModeloDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Nome do Modelo",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "categoria",
                    models.CharField(
                        help_text="Categoria do documento (ex: Petição, Contrato, Parecer)",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(
                        help_text="Conteúdo do documento com variáveis substituíveis",
                        verbose_name="Conteúdo do Modelo",
                    ),
                ),
                (
                    "variaveis",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dicionário com as variáveis disponíveis e suas descrições",
                        verbose_name="Variáveis Disponíveis",
                    ),
                ),
                (
                    "tipo_arquivo",
                    models.CharField(
                        choices=[
                            ("docx", "Word Document (.docx)"),
                            ("pdf", "PDF Document (.pdf)"),
                            ("txt", "Text File (.txt)"),
                            ("html", "HTML Document (.html)"),
                        ],
                        default="docx",
                        max_length=10,
                        verbose_name="Tipo de Arquivo",
                    ),
                ),
                (
                    "publico",
                    models.BooleanField(
                        default=False,
                        help_text="Define se o modelo está disponível para todos os usuários",
                        verbose_name="Público",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "vezes_usado",
                    models.PositiveIntegerField(default=0, verbose_name="Vezes Usado"),
                ),
                (
                    "ultimo_uso",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Uso"
                    ),
                ),
                (
                    "areas_direito",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Áreas do direito relacionadas a este modelo",
                        to="configuracoes.areadireito",
                        verbose_name="Áreas do Direito",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modelos_documento_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "tipos_processo",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tipos de processo relacionados a este modelo",
                        to="configuracoes.tipoprocesso",
                        verbose_name="Tipos de Processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de Documento",
                "verbose_name_plural": "Modelos de Documento",
                "ordering": ["-ultimo_uso", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave",
                    models.CharField(
                        help_text="Identificador único da configuração",
                        max_length=100,
                        unique=True,
                        verbose_name="Chave",
                    ),
                ),
                (
                    "valor",
                    models.TextField(
                        help_text="Valor da configuração", verbose_name="Valor"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("string", "Texto"),
                            ("integer", "Número Inteiro"),
                            ("float", "Número Decimal"),
                            ("boolean", "Verdadeiro/Falso"),
                            ("json", "JSON"),
                            ("date", "Data"),
                            ("datetime", "Data e Hora"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="Tipo de Dados",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição da configuração",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        default="geral",
                        help_text="Categoria da configuração para organização",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "editavel",
                    models.BooleanField(
                        default=True,
                        help_text="Define se a configuração pode ser editada pela interface",
                        verbose_name="Editável",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do Sistema",
                "verbose_name_plural": "Configurações do Sistema",
                "ordering": ["categoria", "chave"],
            },
        ),
        migrations.AddIndex(
            model_name="tipoprocesso",
            index=models.Index(
                fields=["ativo", "ordem"], name="configuraco_ativo_668aeb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tipoprocesso",
            index=models.Index(fields=["codigo"], name="configuraco_codigo_333bfd_idx"),
        ),
        migrations.AddIndex(
            model_name="statusprocesso",
            index=models.Index(
                fields=["ativo", "ordem"], name="configuraco_ativo_093cad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statusprocesso",
            index=models.Index(fields=["codigo"], name="configuraco_codigo_07d7c5_idx"),
        ),
        migrations.AddIndex(
            model_name="statusprocesso",
            index=models.Index(
                fields=["is_inicial"], name="configuraco_is_inic_fcbd55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statusprocesso",
            index=models.Index(
                fields=["is_final"], name="configuraco_is_fina_aaa7a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelodocumento",
            index=models.Index(
                fields=["ativo", "publico"], name="configuraco_ativo_acb6dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelodocumento",
            index=models.Index(
                fields=["categoria"], name="configuraco_categor_673530_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelodocumento",
            index=models.Index(
                fields=["criado_por"], name="configuraco_criado__831264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelodocumento",
            index=models.Index(
                fields=["-vezes_usado"], name="configuraco_vezes_u_23c619_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configuracaosistema",
            index=models.Index(
                fields=["categoria"], name="configuraco_categor_0a0494_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="configuracaosistema",
            index=models.Index(fields=["chave"], name="configuraco_chave_0f1933_idx"),
        ),
        migrations.AddIndex(
            model_name="configuracaosistema",
            index=models.Index(
                fields=["editavel"], name="configuraco_editave_db3ae4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="areadireito",
            index=models.Index(
                fields=["ativo", "ordem"], name="configuraco_ativo_5ee30d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="areadireito",
            index=models.Index(fields=["codigo"], name="configuraco_codigo_1fcb54_idx"),
        ),
    ]
