# Generated by Django 4.2.23 on 2025-08-16 14:51

from django.db import migrations, models
import django.db.models.deletion
import documentos.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompartilhamentoDocumento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_compartilhamento",
                    models.CharField(
                        choices=[
                            ("interno", "Usuário Interno"),
                            ("externo", "E-mail Externo"),
                            ("link_publico", "Link Público"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de Compartilhamento",
                    ),
                ),
                (
                    "email_externo",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="E-mail Externo",
                    ),
                ),
                (
                    "permissao",
                    models.CharField(
                        choices=[
                            ("visualizar", "Apenas Visualizar"),
                            ("download", "Visualizar e Download"),
                        ],
                        default="visualizar",
                        max_length=15,
                        verbose_name="Permissão",
                    ),
                ),
                (
                    "token_acesso",
                    models.CharField(
                        help_text="Token único para acesso ao documento",
                        max_length=64,
                        unique=True,
                        verbose_name="Token de Acesso",
                    ),
                ),
                (
                    "data_expiracao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data limite para acesso (opcional)",
                        null=True,
                        verbose_name="Data de Expiração",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Compartilhamento de Documento",
                "verbose_name_plural": "Compartilhamentos de Documentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único do documento",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome_arquivo",
                    models.CharField(
                        help_text="Nome original do arquivo",
                        max_length=255,
                        verbose_name="Nome do Arquivo",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        help_text="Arquivo digital do documento",
                        upload_to=documentos.models.upload_to_processo,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do conteúdo do documento",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "tamanho_arquivo",
                    models.PositiveIntegerField(
                        help_text="Tamanho do arquivo em bytes",
                        verbose_name="Tamanho do Arquivo (bytes)",
                    ),
                ),
                (
                    "hash_arquivo",
                    models.CharField(
                        help_text="Hash SHA-256 para verificação de integridade",
                        max_length=64,
                        verbose_name="Hash do Arquivo",
                    ),
                ),
                (
                    "extensao",
                    models.CharField(
                        help_text="Extensão do arquivo",
                        max_length=10,
                        verbose_name="Extensão",
                    ),
                ),
                (
                    "confidencialidade",
                    models.CharField(
                        choices=[
                            ("publica", "Pública"),
                            ("interna", "Interna"),
                            ("confidencial", "Confidencial"),
                            ("secreta", "Secreta"),
                        ],
                        default="interna",
                        max_length=15,
                        verbose_name="Nível de Confidencialidade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("arquivado", "Arquivado"),
                            ("excluido", "Excluído"),
                        ],
                        default="ativo",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "versao",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Número da versão do documento",
                        verbose_name="Versão",
                    ),
                ),
                (
                    "palavras_chave",
                    models.CharField(
                        blank=True,
                        help_text="Palavras-chave para busca, separadas por vírgula",
                        max_length=500,
                        null=True,
                        verbose_name="Palavras-chave",
                    ),
                ),
                (
                    "data_documento",
                    models.DateField(
                        blank=True,
                        help_text="Data de criação/emissão do documento",
                        null=True,
                        verbose_name="Data do Documento",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Upload"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da categoria de documento",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome do Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição detalhada do tipo de documento",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "extensoes_permitidas",
                    models.CharField(
                        default="pdf,doc,docx,jpg,jpeg,png,txt",
                        help_text="Extensões de arquivo permitidas, separadas por vírgula",
                        max_length=200,
                        verbose_name="Extensões Permitidas",
                    ),
                ),
                (
                    "tamanho_maximo",
                    models.PositiveIntegerField(
                        default=52428800,
                        help_text="Tamanho máximo do arquivo em bytes",
                        verbose_name="Tamanho Máximo (bytes)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documentos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoAcesso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("visualizacao", "Visualização"),
                            ("download", "Download"),
                            ("compartilhamento", "Compartilhamento"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Endereço IP"),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_acessos",
                        to="documentos.documento",
                        verbose_name="Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Acesso",
                "verbose_name_plural": "Históricos de Acesso",
                "ordering": ["-timestamp"],
            },
        ),
    ]
