# Generated by Django 4.2.23 on 2025-08-16 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("processos", "0001_initial"),
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicoacesso",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="documento_pai",
            field=models.ForeignKey(
                blank=True,
                help_text="Documento original (para controle de versões)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versoes",
                to="documentos.documento",
                verbose_name="Documento Pai",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="processos.processo",
                verbose_name="Processo",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="tipo_documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="documentos.tipodocumento",
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="usuario_upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que fez Upload",
            ),
        ),
        migrations.AddField(
            model_name="compartilhamentodocumento",
            name="documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compartilhamentos",
                to="documentos.documento",
                verbose_name="Documento",
            ),
        ),
        migrations.AddField(
            model_name="compartilhamentodocumento",
            name="usuario_compartilhou",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compartilhamentos_criados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que Compartilhou",
            ),
        ),
        migrations.AddField(
            model_name="compartilhamentodocumento",
            name="usuario_interno",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Interno",
            ),
        ),
        migrations.AddIndex(
            model_name="historicoacesso",
            index=models.Index(
                fields=["documento", "-timestamp"],
                name="documentos__documen_539855_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historicoacesso",
            index=models.Index(
                fields=["usuario", "-timestamp"], name="documentos__usuario_9413c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historicoacesso",
            index=models.Index(fields=["acao"], name="documentos__acao_bf18db_idx"),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["processo", "-created_at"],
                name="documentos__process_06b630_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["tipo_documento"], name="documentos__tipo_do_7b089c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(fields=["status"], name="documentos__status_7a8643_idx"),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["hash_arquivo"], name="documentos__hash_ar_91ec09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["usuario_upload"], name="documentos__usuario_4240f7_idx"
            ),
        ),
    ]
