# Generated by Django 4.2.23 on 2025-08-16 14:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_andamento', models.DateField(verbose_name='Data do Andamento')),
                ('tipo_andamento', models.CharField(choices=[('peticao', 'Petição'), ('decisao', 'Decisão'), ('sentenca', 'Sentença'), ('acordao', 'Acórdão'), ('intimacao', 'Intimação'), ('audiencia', 'Audiência'), ('juntada', 'Juntada'), ('citacao', 'Citação'), ('recurso', 'Recurso'), ('despacho', 'Despacho'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Andamento')),
                ('descricao', models.TextField(help_text='Detalhes do andamento processual', verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações internas sobre o andamento', null=True, verbose_name='Observações Internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Andamento',
                'verbose_name_plural': 'Andamentos',
                'ordering': ['-data_andamento', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_prazo', models.CharField(choices=[('contestacao', 'Contestação'), ('recurso', 'Recurso'), ('manifestacao', 'Manifestação'), ('audiencia', 'Audiência'), ('pericia', 'Perícia'), ('cumprimento', 'Cumprimento de Sentença'), ('embargos', 'Embargos'), ('alegacoes', 'Alegações Finais'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Prazo')),
                ('data_limite', models.DateField(help_text='Data final para cumprimento do prazo', verbose_name='Data Limite')),
                ('data_inicio', models.DateField(blank=True, help_text='Data de início da contagem do prazo', null=True, verbose_name='Data de Início')),
                ('descricao', models.TextField(help_text='Detalhes sobre o que deve ser feito', verbose_name='Descrição')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade')),
                ('cumprido', models.BooleanField(default=False, help_text='Indica se o prazo foi cumprido', verbose_name='Cumprido')),
                ('data_cumprimento', models.DateField(blank=True, null=True, verbose_name='Data de Cumprimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Prazo',
                'verbose_name_plural': 'Prazos',
                'ordering': ['data_limite', 'prioridade'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do processo', primary_key=True, serialize=False)),
                ('numero_processo', models.CharField(help_text='Número único do processo no tribunal', max_length=50, unique=True, verbose_name='Número do Processo')),
                ('tipo_processo', models.CharField(choices=[('judicial', 'Judicial'), ('administrativo', 'Administrativo'), ('consultivo', 'Consultivo'), ('extrajudicial', 'Extrajudicial')], max_length=20, verbose_name='Tipo de Processo')),
                ('area_direito', models.CharField(choices=[('civil', 'Direito Civil'), ('penal', 'Direito Penal'), ('trabalhista', 'Direito Trabalhista'), ('tributario', 'Direito Tributário'), ('empresarial', 'Direito Empresarial'), ('familia', 'Direito de Família'), ('consumidor', 'Direito do Consumidor'), ('previdenciario', 'Direito Previdenciário'), ('administrativo', 'Direito Administrativo'), ('constitucional', 'Direito Constitucional'), ('ambiental', 'Direito Ambiental'), ('imobiliario', 'Direito Imobiliário'), ('outro', 'Outro')], max_length=20, verbose_name='Área do Direito')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado'), ('arquivado', 'Arquivado')], default='ativo', max_length=20, verbose_name='Status')),
                ('instancia', models.CharField(choices=[('1_instancia', '1ª Instância'), ('2_instancia', '2ª Instância'), ('superior', 'Tribunal Superior'), ('supremo', 'Supremo Tribunal')], default='1_instancia', max_length=15, verbose_name='Instância')),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, help_text='Valor econômico do processo', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor da Causa')),
                ('comarca_tribunal', models.CharField(help_text='Nome da comarca ou tribunal', max_length=200, verbose_name='Comarca/Tribunal')),
                ('vara_orgao', models.CharField(blank=True, help_text='Vara ou órgão específico', max_length=200, null=True, verbose_name='Vara/Órgão')),
                ('juiz', models.CharField(blank=True, help_text='Nome do juiz responsável', max_length=200, null=True, verbose_name='Juiz')),
                ('data_inicio', models.DateField(help_text='Data de distribuição ou início do processo', verbose_name='Data de Início')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('assunto', models.CharField(help_text='Resumo do objeto do processo', max_length=500, verbose_name='Assunto')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais sobre o processo', null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-data_inicio', 'numero_processo'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoParteEnvolvida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('polo', models.CharField(choices=[('ativo', 'Polo Ativo'), ('passivo', 'Polo Passivo'), ('terceiro', 'Terceiro')], help_text='Posição da parte no processo', max_length=10, verbose_name='Polo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('parte_envolvida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.parteenvolvida', verbose_name='Parte Envolvida')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Processo - Parte Envolvida',
                'verbose_name_plural': 'Processos - Partes Envolvidas',
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='partes_envolvidas',
            field=models.ManyToManyField(blank=True, through='processos.ProcessoParteEnvolvida', to='clientes.parteenvolvida', verbose_name='Partes Envolvidas'),
        ),
    ]
