# Generated by Django 4.2.23 on 2025-08-16 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="usuario_responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processos_responsavel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Advogado Responsável",
            ),
        ),
        migrations.AddField(
            model_name="prazo",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prazos",
                to="processos.processo",
                verbose_name="Processo",
            ),
        ),
        migrations.AddField(
            model_name="prazo",
            name="usuario_responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Responsável",
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="andamentos",
                to="processos.processo",
                verbose_name="Processo",
            ),
        ),
        migrations.AddField(
            model_name="andamento",
            name="usuario",
            field=models.ForeignKey(
                help_text="Usuário que registrou o andamento",
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Responsável",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="processoparteenvolvida",
            unique_together={("processo", "parte_envolvida")},
        ),
        migrations.AddIndex(
            model_name="processo",
            index=models.Index(
                fields=["numero_processo"], name="processos_p_numero__d17be0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processo",
            index=models.Index(
                fields=["cliente", "-data_inicio"],
                name="processos_p_cliente_6fb6b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processo",
            index=models.Index(
                fields=["usuario_responsavel", "-data_inicio"],
                name="processos_p_usuario_1c9dc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processo",
            index=models.Index(fields=["status"], name="processos_p_status_b5122a_idx"),
        ),
        migrations.AddIndex(
            model_name="processo",
            index=models.Index(
                fields=["area_direito"], name="processos_p_area_di_cc522e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processo",
            index=models.Index(
                fields=["tipo_processo"], name="processos_p_tipo_pr_9d89c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prazo",
            index=models.Index(
                fields=["processo", "data_limite"],
                name="processos_p_process_b8c401_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prazo",
            index=models.Index(
                fields=["data_limite", "cumprido"],
                name="processos_p_data_li_7060ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prazo",
            index=models.Index(
                fields=["usuario_responsavel", "data_limite"],
                name="processos_p_usuario_837ead_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prazo",
            index=models.Index(
                fields=["prioridade"], name="processos_p_priorid_1b0a6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="andamento",
            index=models.Index(
                fields=["processo", "-data_andamento"],
                name="processos_a_process_049ba6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="andamento",
            index=models.Index(
                fields=["tipo_andamento"], name="processos_a_tipo_an_d94db9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="andamento",
            index=models.Index(
                fields=["data_andamento"], name="processos_a_data_an_2de144_idx"
            ),
        ),
    ]
