# Generated by Django 4.2.24 on 2025-09-15 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("prazo_processo", "Prazo Processual"),
                            ("audiencia", "Audiência"),
                            ("reuniao", "Reunião"),
                            ("vencimento_documento", "Vencimento de Documento"),
                            ("pagamento", "Pagamento"),
                            ("tarefa", "Tarefa"),
                            ("evento", "Evento"),
                            ("lembrete", "Lembrete"),
                            ("aniversario", "Aniversário"),
                            ("outro", "Outro"),
                        ],
                        default="lembrete",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                            ("adiado", "Adiado"),
                        ],
                        default="ativo",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_alerta",
                    models.DateTimeField(
                        help_text="Quando o alerta deve ser disparado",
                        verbose_name="Data e Hora do Alerta",
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data limite para a ação (opcional)",
                        null=True,
                        verbose_name="Data de Vencimento",
                    ),
                ),
                (
                    "recorrente",
                    models.BooleanField(
                        default=False,
                        help_text="Se o alerta deve se repetir",
                        verbose_name="Recorrente",
                    ),
                ),
                (
                    "frequencia_recorrencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("diario", "Diário"),
                            ("semanal", "Semanal"),
                            ("mensal", "Mensal"),
                            ("anual", "Anual"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Frequência de Recorrência",
                    ),
                ),
                (
                    "notificar_email",
                    models.BooleanField(
                        default=False, verbose_name="Notificar por Email"
                    ),
                ),
                (
                    "antecedencia_minutos",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Quantos minutos antes disparar o alerta",
                        verbose_name="Antecedência (minutos)",
                    ),
                ),
                (
                    "objeto_tipo",
                    models.CharField(
                        blank=True,
                        help_text="Tipo do objeto relacionado (ex: processo, cliente)",
                        max_length=50,
                        null=True,
                        verbose_name="Tipo do Objeto",
                    ),
                ),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True,
                        help_text="ID do objeto relacionado",
                        max_length=100,
                        null=True,
                        verbose_name="ID do Objeto",
                    ),
                ),
                (
                    "url_acao",
                    models.URLField(
                        blank=True,
                        help_text="URL para onde o usuário será direcionado",
                        null=True,
                        verbose_name="URL de Ação",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "concluido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["data_alerta", "-prioridade"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("criado", "Criado"),
                            ("editado", "Editado"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                            ("adiado", "Adiado"),
                            ("disparado", "Disparado"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "data_acao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Ação"
                    ),
                ),
                (
                    "alerta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="alertas.alerta",
                        verbose_name="Alerta",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Alerta",
                "verbose_name_plural": "Históricos de Alertas",
                "ordering": ["-data_acao"],
            },
        ),
        migrations.CreateModel(
            name="ConfiguracaoAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alertas_ativos",
                    models.BooleanField(
                        default=True,
                        help_text="Receber alertas do sistema",
                        verbose_name="Alertas Ativos",
                    ),
                ),
                (
                    "alertas_prazos",
                    models.BooleanField(default=True, verbose_name="Alertas de Prazos"),
                ),
                (
                    "alertas_audiencias",
                    models.BooleanField(
                        default=True, verbose_name="Alertas de Audiências"
                    ),
                ),
                (
                    "alertas_reunioes",
                    models.BooleanField(
                        default=True, verbose_name="Alertas de Reuniões"
                    ),
                ),
                (
                    "alertas_pagamentos",
                    models.BooleanField(
                        default=True, verbose_name="Alertas de Pagamentos"
                    ),
                ),
                (
                    "alertas_tarefas",
                    models.BooleanField(
                        default=True, verbose_name="Alertas de Tarefas"
                    ),
                ),
                (
                    "notificacao_email",
                    models.BooleanField(
                        default=False, verbose_name="Notificações por Email"
                    ),
                ),
                (
                    "notificacao_push",
                    models.BooleanField(default=True, verbose_name="Notificações Push"),
                ),
                (
                    "antecedencia_padrao",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Antecedência padrão para novos alertas",
                        verbose_name="Antecedência Padrão (minutos)",
                    ),
                ),
                (
                    "horario_inicio",
                    models.TimeField(
                        default="08:00",
                        help_text="Não enviar alertas antes deste horário",
                        verbose_name="Horário de Início",
                    ),
                ),
                (
                    "horario_fim",
                    models.TimeField(
                        default="18:00",
                        help_text="Não enviar alertas após este horário",
                        verbose_name="Horário de Fim",
                    ),
                ),
                (
                    "alertas_fins_semana",
                    models.BooleanField(
                        default=False, verbose_name="Alertas nos Fins de Semana"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_alertas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Alerta",
                "verbose_name_plural": "Configurações de Alertas",
            },
        ),
        migrations.AddIndex(
            model_name="alerta",
            index=models.Index(
                fields=["usuario", "status"], name="alertas_ale_usuario_9d4fda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerta",
            index=models.Index(
                fields=["data_alerta", "status"], name="alertas_ale_data_al_be73ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerta",
            index=models.Index(
                fields=["tipo", "prioridade"], name="alertas_ale_tipo_a4d4a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerta",
            index=models.Index(
                fields=["objeto_tipo", "objeto_id"],
                name="alertas_ale_objeto__a78404_idx",
            ),
        ),
    ]
