# Generated by Django 4.2.24 on 2025-09-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alertas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerta",
            name="notificado_antecedencia",
            field=models.BooleanField(
                default=False,
                help_text="Se já foi enviada notificação de antecedência",
                verbose_name="Notificado Antecedência",
            ),
        ),
        migrations.AddField(
            model_name="alerta",
            name="notificado_vencimento",
            field=models.BooleanField(
                default=False,
                help_text="Se já foi enviada notificação de vencimento",
                verbose_name="Notificado Vencimento",
            ),
        ),
    ]
