# Generated by Django 4.2.23 on 2025-08-16 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferenciaUsuario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tema",
                    models.CharField(
                        choices=[
                            ("light", "Claro"),
                            ("dark", "Escuro"),
                            ("auto", "Automático"),
                        ],
                        default="light",
                        help_text="Tema da interface do usuário",
                        max_length=10,
                        verbose_name="Tema",
                    ),
                ),
                (
                    "idioma",
                    models.CharField(
                        choices=[
                            ("pt-br", "Português (Brasil)"),
                            ("en", "English"),
                            ("es", "Español"),
                        ],
                        default="pt-br",
                        help_text="Idioma da interface",
                        max_length=10,
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("America/Sao_Paulo", "São Paulo (GMT-3)"),
                            ("America/Manaus", "Manaus (GMT-4)"),
                            ("America/Rio_Branco", "Rio Branco (GMT-5)"),
                        ],
                        default="America/Sao_Paulo",
                        help_text="Fuso horário para exibição de datas e horários",
                        max_length=50,
                        verbose_name="Fuso Horário",
                    ),
                ),
                (
                    "items_por_pagina",
                    models.IntegerField(
                        choices=[
                            (10, "10 itens"),
                            (20, "20 itens"),
                            (50, "50 itens"),
                            (100, "100 itens"),
                        ],
                        default=20,
                        help_text="Número de itens exibidos por página nas listagens",
                        verbose_name="Itens por Página",
                    ),
                ),
                (
                    "notificacoes_email",
                    models.BooleanField(
                        default=True,
                        help_text="Receber notificações por e-mail",
                        verbose_name="Notificações por E-mail",
                    ),
                ),
                (
                    "notificacoes_prazos",
                    models.BooleanField(
                        default=True,
                        help_text="Receber alertas sobre prazos próximos",
                        verbose_name="Alertas de Prazos",
                    ),
                ),
                (
                    "notificacoes_sistema",
                    models.BooleanField(
                        default=True,
                        help_text="Receber notificações sobre atualizações do sistema",
                        verbose_name="Notificações do Sistema",
                    ),
                ),
                (
                    "notificacoes_marketing",
                    models.BooleanField(
                        default=False,
                        help_text="Receber e-mails promocionais e newsletters",
                        verbose_name="E-mails Promocionais",
                    ),
                ),
                (
                    "dashboard_widgets",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuração dos widgets exibidos no dashboard",
                        verbose_name="Widgets do Dashboard",
                    ),
                ),
                (
                    "sidebar_collapsed",
                    models.BooleanField(
                        default=False,
                        help_text="Define se a sidebar deve iniciar recolhida",
                        verbose_name="Sidebar Recolhida",
                    ),
                ),
                (
                    "formato_data_preferido",
                    models.CharField(
                        choices=[
                            ("dd/mm/yyyy", "DD/MM/AAAA"),
                            ("mm/dd/yyyy", "MM/DD/AAAA"),
                            ("yyyy-mm-dd", "AAAA-MM-DD"),
                        ],
                        default="dd/mm/yyyy",
                        max_length=20,
                        verbose_name="Formato de Data Preferido",
                    ),
                ),
                (
                    "formato_moeda_preferido",
                    models.CharField(
                        choices=[
                            ("BRL", "Real (R$)"),
                            ("USD", "Dólar ($)"),
                            ("EUR", "Euro (€)"),
                        ],
                        default="BRL",
                        max_length=10,
                        verbose_name="Formato de Moeda Preferido",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferência do Usuário",
                "verbose_name_plural": "Preferências dos Usuários",
                "ordering": ["usuario__first_name", "usuario__last_name"],
            },
        ),
    ]
