# Generated by Django 4.2.23 on 2025-08-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financeiro", "0001_initial"),
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="honorario",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="honorarios",
                to="processos.processo",
                verbose_name="Processo",
            ),
        ),
        migrations.AddField(
            model_name="despesa",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="despesas",
                to="processos.processo",
                verbose_name="Processo",
            ),
        ),
    ]
