# Generated by Django 4.2.23 on 2025-08-16 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financeiro", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="usuario_lancamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário que Lançou",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parcelahonorario",
            unique_together={("honorario", "numero_parcela")},
        ),
        migrations.AddIndex(
            model_name="honorario",
            index=models.Index(
                fields=["processo"], name="financeiro__process_b5262e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="honorario",
            index=models.Index(
                fields=["cliente"], name="financeiro__cliente_368289_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="honorario",
            index=models.Index(
                fields=["status_pagamento"], name="financeiro__status__110afa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="honorario",
            index=models.Index(
                fields=["data_vencimento"], name="financeiro__data_ve_e46551_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="honorario",
            index=models.Index(
                fields=["tipo_cobranca"], name="financeiro__tipo_co_87f7e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(
                fields=["processo", "-data_despesa"],
                name="financeiro__process_150087_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(
                fields=["tipo_despesa"], name="financeiro__tipo_de_cadb9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(
                fields=["status_reembolso"], name="financeiro__status__13ea80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="despesa",
            index=models.Index(
                fields=["data_despesa"], name="financeiro__data_de_a67d0a_idx"
            ),
        ),
    ]
