# Generated by Django 4.2.24 on 2025-09-18 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import financeiro.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financeiro", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoHonorario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único do documento",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome_arquivo",
                    models.CharField(
                        help_text="Nome original do arquivo",
                        max_length=255,
                        verbose_name="Nome do Arquivo",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        help_text="Arquivo do documento (PDF, DOC, DOCX, JPG, PNG)",
                        upload_to=financeiro.models.upload_honorario_documento,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato de Honorários"),
                            ("nota_fiscal", "Nota Fiscal"),
                            ("recibo", "Recibo"),
                            ("comprovante_pagamento", "Comprovante de Pagamento"),
                            ("acordo", "Acordo/Termo"),
                            ("correspondencia", "Correspondência"),
                            ("outro", "Outro"),
                        ],
                        max_length=25,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do conteúdo do documento",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "tamanho_arquivo",
                    models.PositiveIntegerField(
                        help_text="Tamanho do arquivo em bytes",
                        verbose_name="Tamanho do Arquivo (bytes)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Upload"
                    ),
                ),
                (
                    "honorario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="financeiro.honorario",
                        verbose_name="Honorário",
                    ),
                ),
                (
                    "usuario_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário que fez o Upload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Honorário",
                "verbose_name_plural": "Documentos de Honorários",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["honorario", "-created_at"],
                        name="financeiro__honorar_61dbf5_idx",
                    ),
                    models.Index(
                        fields=["tipo_documento"], name="financeiro__tipo_do_d876fd_idx"
                    ),
                ],
            },
        ),
    ]
