# Generated by Django 4.2.23 on 2025-08-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interacaocliente",
            name="processo_relacionado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="processos.processo",
                verbose_name="Processo Relacionado",
            ),
        ),
    ]
