# Generated by Django 4.2.23 on 2025-08-16 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interacaocliente",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Responsável",
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["tipo_pessoa"], name="clientes_cl_tipo_pe_296f14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["nome_razao_social"], name="clientes_cl_nome_ra_45f597_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["cpf_cnpj"], name="clientes_cl_cpf_cnp_0eeb49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["ativo"], name="clientes_cl_ativo_332763_idx"),
        ),
        migrations.AddIndex(
            model_name="interacaocliente",
            index=models.Index(
                fields=["cliente", "-data_interacao"],
                name="clientes_in_cliente_b656f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interacaocliente",
            index=models.Index(
                fields=["tipo_interacao"], name="clientes_in_tipo_in_69ed2e_idx"
            ),
        ),
    ]
