# Generated by Django 4.2.24 on 2025-09-15 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criação"),
                            ("UPDATE", "Atualização"),
                            ("DELETE", "Exclusão"),
                            ("VIEW", "Visualização"),
                            ("EXPORT", "Exportação"),
                        ],
                        max_length=10,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data/Hora"
                    ),
                ),
                (
                    "usuario_nome",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nome do Usuário"
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "dados_anteriores",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Dados Anteriores"
                    ),
                ),
                (
                    "dados_novos",
                    models.JSONField(blank=True, null=True, verbose_name="Dados Novos"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="clientes_au_timesta_2db817_idx"
                    ),
                    models.Index(fields=["acao"], name="clientes_au_acao_0ae11c_idx"),
                    models.Index(
                        fields=["usuario"], name="clientes_au_usuario_7eb133_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="clientes_au_content_b6c8ab_idx",
                    ),
                ],
            },
        ),
    ]
