# Generated by Django 4.2.23 on 2025-08-16 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoNotificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receber_prazo_critico",
                    models.BooleanField(
                        default=True,
                        verbose_name="Receber notificações de prazos críticos",
                    ),
                ),
                (
                    "receber_novo_andamento",
                    models.BooleanField(
                        default=True,
                        verbose_name="Receber notificações de novos andamentos",
                    ),
                ),
                (
                    "receber_documento_upload",
                    models.BooleanField(
                        default=True,
                        verbose_name="Receber notificações de upload de documentos",
                    ),
                ),
                (
                    "receber_financeiro",
                    models.BooleanField(
                        default=True, verbose_name="Receber notificações financeiras"
                    ),
                ),
                (
                    "receber_sistema",
                    models.BooleanField(
                        default=True, verbose_name="Receber notificações do sistema"
                    ),
                ),
                (
                    "notificacao_email",
                    models.BooleanField(
                        default=False, verbose_name="Receber notificações por email"
                    ),
                ),
                (
                    "dias_antecedencia_prazo",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Quantos dias antes do vencimento enviar alerta",
                        verbose_name="Dias de antecedência para alertas de prazo",
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_notificacoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Notificação",
                "verbose_name_plural": "Configurações de Notificação",
            },
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("prazo_critico", "Prazo Crítico"),
                            ("prazo_vencido", "Prazo Vencido"),
                            ("novo_andamento", "Novo Andamento"),
                            ("documento_upload", "Documento Enviado"),
                            ("sistema", "Sistema"),
                            ("financeiro", "Financeiro"),
                            ("cliente", "Cliente"),
                            ("processo", "Processo"),
                            ("sucesso", "Sucesso"),
                            ("erro", "Erro"),
                            ("aviso", "Aviso"),
                            ("info", "Informação"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Prioridade",
                    ),
                ),
                ("lida", models.BooleanField(default=False, verbose_name="Lida")),
                (
                    "url_acao",
                    models.URLField(
                        blank=True,
                        help_text="URL para onde o usuário será direcionado ao clicar na notificação",
                        null=True,
                        verbose_name="URL de Ação",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Classe do ícone Bootstrap Icons (ex: bi-bell)",
                        max_length=50,
                        null=True,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "objeto_tipo",
                    models.CharField(
                        blank=True,
                        help_text="Tipo do objeto relacionado (ex: processo, cliente)",
                        max_length=50,
                        null=True,
                        verbose_name="Tipo do Objeto",
                    ),
                ),
                (
                    "objeto_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID do objeto relacionado",
                        null=True,
                        verbose_name="ID do Objeto",
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "lida_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lida em"),
                ),
                (
                    "expira_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data de expiração da notificação (opcional)",
                        null=True,
                        verbose_name="Expira em",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-criada_em"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "-criada_em"],
                        name="notificacoe_usuario_ea8f60_idx",
                    ),
                    models.Index(
                        fields=["usuario", "lida"],
                        name="notificacoe_usuario_a5894e_idx",
                    ),
                    models.Index(
                        fields=["tipo", "prioridade"],
                        name="notificacoe_tipo_55d1c9_idx",
                    ),
                ],
            },
        ),
    ]
