# Generated by Django 4.2.24 on 2025-09-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notificacoes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacao",
            name="objeto_id",
            field=models.CharField(
                blank=True,
                help_text="ID do objeto relacionado",
                max_length=100,
                null=True,
                verbose_name="ID do Objeto",
            ),
        ),
    ]
